## Numpy Array operations

In [1]:
import numpy as np

In [3]:
arr = np.arange(1, 11)
print(arr[2:7]) # basic slicing

[3 4 5 6 7]


In [4]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Specific element: ", arr[1, 2])
print("Entire row: ", arr[1])
print("Entire column: ", arr[:, 1])

Specific element:  6
Entire row:  [4 5 6]
Entire column:  [2 5 8]


- Sorting

In [8]:
unsorted = np.array([3,1,5,7,2,3,3,1])
print("Sorted array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1], [1,2], [2,3]])
print("Sorted 2D array by column: \n", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by row: \n", np.sort(arr_2d_unsorted, axis=1))

Sorted array:  [1 1 2 3 3 3 5 7]
Sorted 2D array by column: 
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row: 
 [[1 3]
 [1 2]
 [2 3]]


- Filter

In [9]:
numbers = np.arange(1, 11)
even_numbers = numbers[numbers % 2 == 0]
print(even_numbers)

[ 2  4  6  8 10]


- Filter with mask

In [10]:
mask = numbers > 5
print("Number greated than 5: ", numbers[mask])

Number greated than 5:  [ 6  7  8  9 10]


- Fancy indexing vs np.where()

In [12]:
indices = [0, 2, 4] # 0th value, 2nd value and 4th value
print(numbers[indices])

[1 3 5]


In [15]:
where_result = np.where(numbers > 5)
print(where_result)
print(numbers[where_result])

(array([5, 6, 7, 8, 9]),)
[ 6  7  8  9 10]


In [16]:
condition_array = np.where(numbers > 5, numbers * 5, numbers)
print(condition_array)

[ 1  2  3  4  5 30 35 40 45 50]


- Adding and removing data

In [17]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


- Array compatibility

In [19]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9,10])

print("Compatibility shapes: ", arr1.shape == arr2.shape)
print("Compatibility shapes: ", arr1.shape == arr3.shape)

Compatibility shapes:  True
Compatibility shapes:  False


In [21]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((original, new_row))
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [23]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 4)
print(deleted)

[1 2 3 4]
