In [1]:
import numpy as np

## Creating array from the list

In [4]:
arr_1 = np.array([1,2,3,4,5])
print("arr1D", arr_1)

arr_2 = np.array([[1,2,3], [4,5,6]])
print("arr2D", arr_2)

arr1D [1 2 3 4 5]
arr2D [[1 2 3]
 [4 5 6]]


- Difference between list and numpy array

In [6]:
py_list = [1,2,3]
print(py_list * 2)

np_array = np.array([1,2,3])
print(np_array * 2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [7]:
import time
start = time.time()
py_list = [i * 2 for i in range(1000000)]
print("List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("Numpy operation time: ", time.time() - start)

List operation time:  0.27643728256225586
Numpy operation time:  0.009026050567626953


- Creating array from scratch

In [13]:
zeros = np.zeros((3, 4))
print(zeros)

ones = np.ones((3, 4))
print(ones)

full = np.full((3, 3), 5)
print(full)

random = np.random.random((5, 7)) # always between 0 - 1
print(random)

sequence = np.arange(0, 10, 2)
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[0.39360564 0.68376416 0.54146411 0.57457048 0.80512067 0.67400045
  0.90854761]
 [0.25906035 0.97852073 0.88613287 0.6266463  0.06689292 0.77535367
  0.79282967]
 [0.98855177 0.27748722 0.47726067 0.43468113 0.61839342 0.60861075
  0.78724806]
 [0.19723717 0.34540962 0.79609914 0.93989427 0.00839968 0.5506767
  0.5310048 ]
 [0.56489356 0.13615852 0.11584109 0.12532579 0.73808207 0.26004607
  0.57203198]]
[0 2 4 6 8]


## Vector, Matrix and Tensor

In [16]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1,2,3], [4,5,6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


- Array properties

In [18]:
arr = np.array([[1,2,4], [4,5,6]])
print("Shape: ", arr.shape)
print("Dimention: ", arr.ndim)
print("Size: ", arr.size)
print("DType: ", arr.dtype)

Shape:  (2, 3)
Dimention:  2
Size:  6
DType:  int64


- Array Reshaping

In [24]:
arr = np.arange(12)
print("Original array: ", arr)

reshaped = arr.reshape((3, 4))
print("Reshaped array: \n", reshaped)

flattened = reshaped.flatten()
print("Flattened array: ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("Raveled array: ", raveled)

# Transpose
transpose = reshaped.T
print("Transposed array: \n", transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
